### ISSUE TITLE
MP Client Crash

### ISSUE THREAD

**Issue by TheBambino** [JustReq/EchoEverything#1]
Upon connecting to a dedicated server with EchoEverything, clients crash. Server produces no errors.

[client.log](https://hastebin.com/opateguqum.yaml)

**Comment by JustReq** [comment]
Hey @TheBambino,
Thank you so much for playing with my mod! I reviewed your client log and tested it out myself. Your issue seems to be present because of the amount of mods you have installed at the same time and the specific mods you have installed. Specifically, I found some compatibility issues with the NPC Control mod, as well as texture errors due to the size of your mod pack. Unfortunately, this is not something I can fix until I know that NPC Control mod is behind a potential crash, so if you could get a proper assessment of the bug, that'd help in finding out what the issues between the two are 👍🏻

Also keep in mind the fact that you shouldn't accept invites until you are past the "Join via Steam" option, since that crashes the game because of a tML bug, which, again, I have no control over.

**Comment by TheBambino** [comment]
Seems to have been one of the mods I used contained in log. I think it's safe to close this issue now.
